spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sampledb
    username: sampledbuser
    password: sampledbpassword
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      auto-commit: false
